# Generated by Django 3.2.9 on 2021-11-07 01:05

import convite.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default=convite.models.create_if_hash, max_length=10, null=True, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(blank=True, max_length=255, null=True)),
                ('presente', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='convite.evento')),
            ],
        ),
    ]
